mykey = "richer-lesson1"
ami = "ami-06c68f701d8090592"
region = "us-east-1"
instance_type = "t3a.medium"
nexus_server_secgr = "petclinic-nexus-server-secgr"
nexus-server-tag = "Nexus Server of Petclinic"